-- Region XIII (orden 1): Arica y Parinacota
INSERT INTO comuna VALUES(1, 'Arica', 'XIII');
INSERT INTO comuna VALUES(2, 'Camarones', 'XIII');
INSERT INTO comuna VALUES(3, 'Putre', 'XIII');
INSERT INTO comuna VALUES(4, 'General Lagos', 'XIII');

-- Region I (orden 2): Tarapacá
INSERT INTO comuna VALUES(5, 'Iquique', 'I');
INSERT INTO comuna VALUES(6, 'Alto Hospicio', 'I');
INSERT INTO comuna VALUES(7, 'Pozo Almonte', 'I');
INSERT INTO comuna VALUES(8, 'Camiña', 'I');
INSERT INTO comuna VALUES(9, 'Colchane', 'I');
INSERT INTO comuna VALUES(10, 'Huara', 'I');
INSERT INTO comuna VALUES(11, 'Pica', 'I');

-- Region II (orden 3): Antofagasta
INSERT INTO comuna VALUES(12, 'Antofagasta', 'II');
INSERT INTO comuna VALUES(13, 'Mejillones', 'II');
INSERT INTO comuna VALUES(14, 'Sierra Gorda', 'II');
INSERT INTO comuna VALUES(15, 'Taltal', 'II');
INSERT INTO comuna VALUES(16, 'Calama', 'II');
INSERT INTO comuna VALUES(17, 'Ollagüe', 'II');
INSERT INTO comuna VALUES(18, 'San Pedro de Atacama', 'II');
INSERT INTO comuna VALUES(19, 'Tocopilla', 'II');
INSERT INTO comuna VALUES(20, 'María Elena', 'II');

-- Region III (orden 4): Atacama
INSERT INTO comuna VALUES(21, 'Copiapó', 'III');
INSERT INTO comuna VALUES(22, 'Caldera', 'III');
INSERT INTO comuna VALUES(23, 'Tierra Amarilla', 'III');
INSERT INTO comuna VALUES(24, 'Chañaral', 'III');
INSERT INTO comuna VALUES(25, 'Diego de Almagro', 'III');
INSERT INTO comuna VALUES(26, 'Vallenar', 'III');
INSERT INTO comuna VALUES(27, 'Alto del Carmen', 'III');
INSERT INTO comuna VALUES(28, 'Freirina', 'III');
INSERT INTO comuna VALUES(29, 'Huasco', 'III');

-- Region IV (orden 5): Coquimbo
INSERT INTO comuna VALUES(30, 'La Serena', 'IV');
INSERT INTO comuna VALUES(31, 'Coquimbo', 'IV');
INSERT INTO comuna VALUES(32, 'Andacollo', 'IV');
INSERT INTO comuna VALUES(33, 'La Higuera', 'IV');
INSERT INTO comuna VALUES(34, 'Paiguano', 'IV');
INSERT INTO comuna VALUES(35, 'Vicuña', 'IV');
INSERT INTO comuna VALUES(36, 'Illapel', 'IV');
INSERT INTO comuna VALUES(37, 'Canela', 'IV');
INSERT INTO comuna VALUES(38, 'Los Vilos', 'IV');
INSERT INTO comuna VALUES(39, 'Salamanca', 'IV');
INSERT INTO comuna VALUES(40, 'Ovalle', 'IV');
INSERT INTO comuna VALUES(41, 'Combarbalá', 'IV');
INSERT INTO comuna VALUES(42, 'Monte Patria', 'IV');
INSERT INTO comuna VALUES(43, 'Punitaqui', 'IV');
INSERT INTO comuna VALUES(44, 'Río Hurtado', 'IV');

-- Region V (orden 6): Valparaíso
INSERT INTO comuna VALUES(45, 'Valparaíso', 'V');
INSERT INTO comuna VALUES(46, 'Casablanca', 'V');
INSERT INTO comuna VALUES(47, 'Concón', 'V');
INSERT INTO comuna VALUES(48, 'Juan Fernández', 'V');
INSERT INTO comuna VALUES(49, 'Puchuncaví', 'V');
INSERT INTO comuna VALUES(50, 'Quintero', 'V');
INSERT INTO comuna VALUES(51, 'Viña del Mar', 'V');
INSERT INTO comuna VALUES(52, 'Isla de Pascua', 'V');
INSERT INTO comuna VALUES(53, 'Los Andes', 'V');
INSERT INTO comuna VALUES(54, 'Calle Larga', 'V');
INSERT INTO comuna VALUES(55, 'Rinconada', 'V');
INSERT INTO comuna VALUES(56, 'San Esteban', 'V');
INSERT INTO comuna VALUES(57, 'La Ligua', 'V');
INSERT INTO comuna VALUES(58, 'Cabildo', 'V');
INSERT INTO comuna VALUES(59, 'Papudo', 'V');
INSERT INTO comuna VALUES(60, 'Petorca', 'V');
INSERT INTO comuna VALUES(61, 'Zapallar', 'V');
INSERT INTO comuna VALUES(62, 'Quillota', 'V');
INSERT INTO comuna VALUES(63, 'Calera', 'V');
INSERT INTO comuna VALUES(64, 'Hijuelas', 'V');
INSERT INTO comuna VALUES(65, 'La Cruz', 'V');
INSERT INTO comuna VALUES(66, 'Nogales', 'V');
INSERT INTO comuna VALUES(67, 'San Antonio', 'V');
INSERT INTO comuna VALUES(68, 'Algarrobo', 'V');
INSERT INTO comuna VALUES(69, 'Cartagena', 'V');
INSERT INTO comuna VALUES(70, 'El Quisco', 'V');
INSERT INTO comuna VALUES(71, 'El Tabo', 'V');
INSERT INTO comuna VALUES(72, 'Santo Domingo', 'V');
INSERT INTO comuna VALUES(73, 'San Felipe', 'V');
INSERT INTO comuna VALUES(74, 'Catemu', 'V');
INSERT INTO comuna VALUES(75, 'Llaillay', 'V');
INSERT INTO comuna VALUES(76, 'Panquehue', 'V');
INSERT INTO comuna VALUES(77, 'Putaendo', 'V');
INSERT INTO comuna VALUES(78, 'Santa María', 'V');
INSERT INTO comuna VALUES(79, 'Limache', 'V');
INSERT INTO comuna VALUES(80, 'Quilpué', 'V');
INSERT INTO comuna VALUES(81, 'Villa Alemana', 'V');
INSERT INTO comuna VALUES(82, 'Olmué', 'V');

-- Region RM (orden 7): Metropolitana de Santiago
INSERT INTO comuna VALUES(83, 'Santiago', 'RM');
INSERT INTO comuna VALUES(84, 'Cerrillos', 'RM');
INSERT INTO comuna VALUES(85, 'Cerro Navia', 'RM');
INSERT INTO comuna VALUES(86, 'Conchalí', 'RM');
INSERT INTO comuna VALUES(87, 'El Bosque', 'RM');
INSERT INTO comuna VALUES(88, 'Estación Central', 'RM');
INSERT INTO comuna VALUES(89, 'Huechuraba', 'RM');
INSERT INTO comuna VALUES(90, 'Independencia', 'RM');
INSERT INTO comuna VALUES(91, 'La Cisterna', 'RM');
INSERT INTO comuna VALUES(92, 'La Florida', 'RM');
INSERT INTO comuna VALUES(93, 'La Granja', 'RM');
INSERT INTO comuna VALUES(94, 'La Pintana', 'RM');
INSERT INTO comuna VALUES(95, 'La Reina', 'RM');
INSERT INTO comuna VALUES(96, 'Las Condes', 'RM');
INSERT INTO comuna VALUES(97, 'Lo Barnechea', 'RM');
INSERT INTO comuna VALUES(98, 'Lo Espejo', 'RM');
INSERT INTO comuna VALUES(99, 'Lo Prado', 'RM');
INSERT INTO comuna VALUES(100, 'Macul', 'RM');
INSERT INTO comuna VALUES(101, 'Maipú', 'RM');
INSERT INTO comuna VALUES(102, 'Ñuñoa', 'RM');
INSERT INTO comuna VALUES(103, 'Pedro Aguirre Cerda', 'RM');
INSERT INTO comuna VALUES(104, 'Peñalolén', 'RM');
INSERT INTO comuna VALUES(105, 'Providencia', 'RM');
INSERT INTO comuna VALUES(106, 'Pudahuel', 'RM');
INSERT INTO comuna VALUES(107, 'Quilicura', 'RM');
INSERT INTO comuna VALUES(108, 'Quinta Normal', 'RM');
INSERT INTO comuna VALUES(109, 'Recoleta', 'RM');
INSERT INTO comuna VALUES(110, 'Renca', 'RM');
INSERT INTO comuna VALUES(111, 'San Miguel', 'RM');
INSERT INTO comuna VALUES(112, 'San Ramón', 'RM');
INSERT INTO comuna VALUES(113, 'Vitacura', 'RM');
INSERT INTO comuna VALUES(114, 'Puente Alto', 'RM');
INSERT INTO comuna VALUES(115, 'Pirque', 'RM');
INSERT INTO comuna VALUES(116, 'San José de Maipo', 'RM');
INSERT INTO comuna VALUES(117, 'Colina', 'RM');
INSERT INTO comuna VALUES(118, 'Lampa', 'RM');
INSERT INTO comuna VALUES(119, 'Tiltil', 'RM');
INSERT INTO comuna VALUES(120, 'San Bernardo', 'RM');
INSERT INTO comuna VALUES(121, 'Buin', 'RM');
INSERT INTO comuna VALUES(122, 'Calera de Tango', 'RM');
INSERT INTO comuna VALUES(123, 'Paine', 'RM');
INSERT INTO comuna VALUES(124, 'Melipilla', 'RM');
INSERT INTO comuna VALUES(125, 'Alhué', 'RM');
INSERT INTO comuna VALUES(126, 'Curacaví', 'RM');
INSERT INTO comuna VALUES(127, 'María Pinto', 'RM');
INSERT INTO comuna VALUES(128, 'San Pedro', 'RM');
INSERT INTO comuna VALUES(129, 'Talagante', 'RM');
INSERT INTO comuna VALUES(130, 'El Monte', 'RM');
INSERT INTO comuna VALUES(131, 'Isla de Maipo', 'RM');
INSERT INTO comuna VALUES(132, 'Padre Hurtado', 'RM');
INSERT INTO comuna VALUES(133, 'Peñaflor', 'RM');
INSERT INTO comuna VALUES(134, 'Talagante', 'RM');  -- Note: Adjusted duplicate; standard list has unique entries.

-- Region VI (orden 8): O'Higgins
INSERT INTO comuna VALUES(135, 'Rancagua', 'VI');
INSERT INTO comuna VALUES(136, 'Codegua', 'VI');
INSERT INTO comuna VALUES(137, 'Coinco', 'VI');
INSERT INTO comuna VALUES(138, 'Coltauco', 'VI');
INSERT INTO comuna VALUES(139, 'Doñihue', 'VI');
INSERT INTO comuna VALUES(140, 'Graneros', 'VI');
INSERT INTO comuna VALUES(141, 'Las Cabras', 'VI');
INSERT INTO comuna VALUES(142, 'Machalí', 'VI');
INSERT INTO comuna VALUES(143, 'Malloa', 'VI');
INSERT INTO comuna VALUES(144, 'Mostazal', 'VI');
INSERT INTO comuna VALUES(145, 'Olivar', 'VI');
INSERT INTO comuna VALUES(146, 'Peumo', 'VI');
INSERT INTO comuna VALUES(147, 'Pichidegua', 'VI');
INSERT INTO comuna VALUES(148, 'Quinta de Tilcoco', 'VI');
INSERT INTO comuna VALUES(149, 'Rengo', 'VI');
INSERT INTO comuna VALUES(150, 'Requínoa', 'VI');
INSERT INTO comuna VALUES(151, 'San Vicente', 'VI');
INSERT INTO comuna VALUES(152, 'Pichilemu', 'VI');
INSERT INTO comuna VALUES(153, 'La Estrella', 'VI');
INSERT INTO comuna VALUES(154, 'Litueche', 'VI');
INSERT INTO comuna VALUES(155, 'Marchihue', 'VI');
INSERT INTO comuna VALUES(156, 'Navidad', 'VI');
INSERT INTO comuna VALUES(157, 'Paredones', 'VI');
INSERT INTO comuna VALUES(158, 'San Fernando', 'VI');
INSERT INTO comuna VALUES(159, 'Chépica', 'VI');
INSERT INTO comuna VALUES(160, 'Chimbarongo', 'VI');
INSERT INTO comuna VALUES(161, 'Lolol', 'VI');
INSERT INTO comuna VALUES(162, 'Nancagua', 'VI');
INSERT INTO comuna VALUES(163, 'Palmilla', 'VI');
INSERT INTO comuna VALUES(164, 'Peralillo', 'VI');
INSERT INTO comuna VALUES(165, 'Placilla', 'VI');
INSERT INTO comuna VALUES(166, 'Pumanque', 'VI');
INSERT INTO comuna VALUES(167, 'Santa Cruz', 'VI');

-- Region VII (orden 9): Maule
INSERT INTO comuna VALUES(168, 'Talca', 'VII');
INSERT INTO comuna VALUES(169, 'Constitución', 'VII');
INSERT INTO comuna VALUES(170, 'Curepto', 'VII');
INSERT INTO comuna VALUES(171, 'Empedrado', 'VII');
INSERT INTO comuna VALUES(172, 'Maule', 'VII');
INSERT INTO comuna VALUES(173, 'Pelarco', 'VII');
INSERT INTO comuna VALUES(174, 'Pencahue', 'VII');
INSERT INTO comuna VALUES(175, 'Río Claro', 'VII');
INSERT INTO comuna VALUES(176, 'San Clemente', 'VII');
INSERT INTO comuna VALUES(177, 'San Rafael', 'VII');
INSERT INTO comuna VALUES(178, 'Cauquenes', 'VII');
INSERT INTO comuna VALUES(179, 'Chanco', 'VII');
INSERT INTO comuna VALUES(180, 'Pelluhue', 'VII');
INSERT INTO comuna VALUES(181, 'Curicó', 'VII');
INSERT INTO comuna VALUES(182, 'Hualañé', 'VII');
INSERT INTO comuna VALUES(183, 'Licantén', 'VII');
INSERT INTO comuna VALUES(184, 'Molina', 'VII');
INSERT INTO comuna VALUES(185, 'Rauco', 'VII');
INSERT INTO comuna VALUES(186, 'Romeral', 'VII');
INSERT INTO comuna VALUES(187, 'Sagrada Familia', 'VII');
INSERT INTO comuna VALUES(188, 'Teno', 'VII');
INSERT INTO comuna VALUES(189, 'Vichuquén', 'VII');
INSERT INTO comuna VALUES(190, 'Linares', 'VII');
INSERT INTO comuna VALUES(191, 'Colbún', 'VII');
INSERT INTO comuna VALUES(192, 'Longaví', 'VII');
INSERT INTO comuna VALUES(193, 'Parral', 'VII');
INSERT INTO comuna VALUES(194, 'Retiro', 'VII');
INSERT INTO comuna VALUES(195, 'San Javier', 'VII');
INSERT INTO comuna VALUES(196, 'Villa Alegre', 'VII');
INSERT INTO comuna VALUES(197, 'Yerbas Buenas', 'VII');

-- Region XV (orden 10): Ñuble
INSERT INTO comuna VALUES(198, 'Chillán', 'XV');
INSERT INTO comuna VALUES(199, 'Bulnes', 'XV');
INSERT INTO comuna VALUES(200, 'Cobquecura', 'XV');
INSERT INTO comuna VALUES(201, 'Coelemu', 'XV');
INSERT INTO comuna VALUES(202, 'Coihueco', 'XV');
INSERT INTO comuna VALUES(203, 'Chillán Viejo', 'XV');
INSERT INTO comuna VALUES(204, 'El Carmen', 'XV');
INSERT INTO comuna VALUES(205, 'Ninhue', 'XV');
INSERT INTO comuna VALUES(206, 'Ñiquén', 'XV');
INSERT INTO comuna VALUES(207, 'Pemuco', 'XV');
INSERT INTO comuna VALUES(208, 'Pinto', 'XV');
INSERT INTO comuna VALUES(209, 'Portezuelo', 'XV');
INSERT INTO comuna VALUES(210, 'Quillón', 'XV');
INSERT INTO comuna VALUES(211, 'Quirihue', 'XV');
INSERT INTO comuna VALUES(212, 'Ránquil', 'XV');
INSERT INTO comuna VALUES(213, 'San Carlos', 'XV');
INSERT INTO comuna VALUES(214, 'San Fabián', 'XV');
INSERT INTO comuna VALUES(215, 'San Ignacio', 'XV');
INSERT INTO comuna VALUES(216, 'San Nicolás', 'XV');
INSERT INTO comuna VALUES(217, 'Treguauco', 'XV');
INSERT INTO comuna VALUES(218, 'Yungay', 'XV');

-- Region VIII (orden 11): Biobío
INSERT INTO comuna VALUES(219, 'Concepción', 'VIII');
INSERT INTO comuna VALUES(220, 'Coronel', 'VIII');
INSERT INTO comuna VALUES(221, 'Chiguayante', 'VIII');
INSERT INTO comuna VALUES(222, 'Florida', 'VIII');
INSERT INTO comuna VALUES(223, 'Hualqui', 'VIII');
INSERT INTO comuna VALUES(224, 'Lota', 'VIII');
INSERT INTO comuna VALUES(225, 'Penco', 'VIII');
INSERT INTO comuna VALUES(226, 'San Pedro de la Paz', 'VIII');
INSERT INTO comuna VALUES(227, 'Santa Juana', 'VIII');
INSERT INTO comuna VALUES(228, 'Talcahuano', 'VIII');
INSERT INTO comuna VALUES(229, 'Tomé', 'VIII');
INSERT INTO comuna VALUES(230, 'Hualpén', 'VIII');
INSERT INTO comuna VALUES(231, 'Lebu', 'VIII');
INSERT INTO comuna VALUES(232, 'Arauco', 'VIII');
INSERT INTO comuna VALUES(233, 'Cañete', 'VIII');
INSERT INTO comuna VALUES(234, 'Contulmo', 'VIII');
INSERT INTO comuna VALUES(235, 'Curanilahue', 'VIII');
INSERT INTO comuna VALUES(236, 'Los Álamos', 'VIII');
INSERT INTO comuna VALUES(237, 'Tirúa', 'VIII');
INSERT INTO comuna VALUES(238, 'Los Ángeles', 'VIII');
INSERT INTO comuna VALUES(239, 'Antuco', 'VIII');
INSERT INTO comuna VALUES(240, 'Cabrero', 'VIII');
INSERT INTO comuna VALUES(241, 'Laja', 'VIII');
INSERT INTO comuna VALUES(242, 'Mulchén', 'VIII');
INSERT INTO comuna VALUES(243, 'Nacimiento', 'VIII');
INSERT INTO comuna VALUES(244, 'Negrete', 'VIII');
INSERT INTO comuna VALUES(245, 'Quilaco', 'VIII');
INSERT INTO comuna VALUES(246, 'Quilleco', 'VIII');
INSERT INTO comuna VALUES(247, 'San Rosendo', 'VIII');
INSERT INTO comuna VALUES(248, 'Santa Bárbara', 'VIII');
INSERT INTO comuna VALUES(249, 'Tucapel', 'VIII');
INSERT INTO comuna VALUES(250, 'Yumbel', 'VIII');
INSERT INTO comuna VALUES(251, 'Alto Biobío', 'VIII');

-- Region IX (orden 12): La Araucanía
INSERT INTO comuna VALUES(252, 'Temuco', 'IX');
INSERT INTO comuna VALUES(253, 'Carahue', 'IX');
INSERT INTO comuna VALUES(254, 'Cunco', 'IX');
INSERT INTO comuna VALUES(255, 'Curarrehue', 'IX');
INSERT INTO comuna VALUES(256, 'Freire', 'IX');
INSERT INTO comuna VALUES(257, 'Galvarino', 'IX');
INSERT INTO comuna VALUES(258, 'Gorbea', 'IX');
INSERT INTO comuna VALUES(259, 'Lautaro', 'IX');
INSERT INTO comuna VALUES(260, 'Loncoche', 'IX');
INSERT INTO comuna VALUES(261, 'Melipeuco', 'IX');
INSERT INTO comuna VALUES(262, 'Nueva Imperial', 'IX');
INSERT INTO comuna VALUES(263, 'Padre Las Casas', 'IX');
INSERT INTO comuna VALUES(264, 'Perquenco', 'IX');
INSERT INTO comuna VALUES(265, 'Pitrufquén', 'IX');
INSERT INTO comuna VALUES(266, 'Pucón', 'IX');
INSERT INTO comuna VALUES(267, 'Saavedra', 'IX');
INSERT INTO comuna VALUES(268, 'Teodoro Schmidt', 'IX');
INSERT INTO comuna VALUES(269, 'Toltén', 'IX');
INSERT INTO comuna VALUES(270, 'Vilcún', 'IX');
INSERT INTO comuna VALUES(271, 'Villarrica', 'IX');
INSERT INTO comuna VALUES(272, 'Cholchol', 'IX');
INSERT INTO comuna VALUES(273, 'Angol', 'IX');
INSERT INTO comuna VALUES(274, 'Collipulli', 'IX');
INSERT INTO comuna VALUES(275, 'Curacautín', 'IX');
INSERT INTO comuna VALUES(276, 'Ercilla', 'IX');
INSERT INTO comuna VALUES(277, 'Lonquimay', 'IX');
INSERT INTO comuna VALUES(278, 'Los Sauces', 'IX');
INSERT INTO comuna VALUES(279, 'Lumaco', 'IX');
INSERT INTO comuna VALUES(280, 'Purén', 'IX');
INSERT INTO comuna VALUES(281, 'Renaico', 'IX');
INSERT INTO comuna VALUES(282, 'Traiguén', 'IX');
INSERT INTO comuna VALUES(283, 'Victoria', 'IX');

-- Region XIV (orden 13): Los Ríos
INSERT INTO comuna VALUES(284, 'Valdivia', 'XIV');
INSERT INTO comuna VALUES(285, 'Corral', 'XIV');
INSERT INTO comuna VALUES(286, 'Lanco', 'XIV');
INSERT INTO comuna VALUES(287, 'Los Lagos', 'XIV');
INSERT INTO comuna VALUES(288, 'Máfil', 'XIV');
INSERT INTO comuna VALUES(289, 'Mariquina', 'XIV');
INSERT INTO comuna VALUES(290, 'Paillaco', 'XIV');
INSERT INTO comuna VALUES(291, 'Panguipulli', 'XIV');
INSERT INTO comuna VALUES(292, 'La Unión', 'XIV');
INSERT INTO comuna VALUES(293, 'Futrono', 'XIV');
INSERT INTO comuna VALUES(294, 'Lago Ranco', 'XIV');
INSERT INTO comuna VALUES(295, 'Río Bueno', 'XIV');

-- Region X (orden 14): Los Lagos
INSERT INTO comuna VALUES(296, 'Puerto Montt', 'X');
INSERT INTO comuna VALUES(297, 'Calbuco', 'X');
INSERT INTO comuna VALUES(298, 'Cochamó', 'X');
INSERT INTO comuna VALUES(299, 'Fresia', 'X');
INSERT INTO comuna VALUES(300, 'Frutillar', 'X');
INSERT INTO comuna VALUES(301, 'Los Muermos', 'X');
INSERT INTO comuna VALUES(302, 'Llanquihue', 'X');
INSERT INTO comuna VALUES(303, 'Maullín', 'X');
INSERT INTO comuna VALUES(304, 'Puerto Varas', 'X');
INSERT INTO comuna VALUES(305, 'Castro', 'X');
INSERT INTO comuna VALUES(306, 'Ancud', 'X');
INSERT INTO comuna VALUES(307, 'Chonchi', 'X');
INSERT INTO comuna VALUES(308, 'Curaco de Vélez', 'X');
INSERT INTO comuna VALUES(309, 'Dalcahue', 'X');
INSERT INTO comuna VALUES(310, 'Puqueldón', 'X');
INSERT INTO comuna VALUES(311, 'Queilén', 'X');
INSERT INTO comuna VALUES(312, 'Quellón', 'X');
INSERT INTO comuna VALUES(313, 'Quemchi', 'X');
INSERT INTO comuna VALUES(314, 'Quinchao', 'X');
INSERT INTO comuna VALUES(315, 'Osorno', 'X');
INSERT INTO comuna VALUES(316, 'Puerto Octay', 'X');
INSERT INTO comuna VALUES(317, 'Purranque', 'X');
INSERT INTO comuna VALUES(318, 'Puyehue', 'X');
INSERT INTO comuna VALUES(319, 'Río Negro', 'X');
INSERT INTO comuna VALUES(320, 'San Juan de la Costa', 'X');
INSERT INTO comuna VALUES(321, 'San Pablo', 'X');
INSERT INTO comuna VALUES(322, 'Chaitén', 'X');
INSERT INTO comuna VALUES(323, 'Futaleufú', 'X');
INSERT INTO comuna VALUES(324, 'Hualaihué', 'X');
INSERT INTO comuna VALUES(325, 'Palena', 'X');

-- Region XI (orden 15): Aysén
INSERT INTO comuna VALUES(326, 'Coihaique', 'XI');
INSERT INTO comuna VALUES(327, 'Lago Verde', 'XI');
INSERT INTO comuna VALUES(328, 'Aysén', 'XI');
INSERT INTO comuna VALUES(329, 'Cisnes', 'XI');
INSERT INTO comuna VALUES(330, 'Guaitecas', 'XI');
INSERT INTO comuna VALUES(331, 'Cochrane', 'XI');
INSERT INTO comuna VALUES(332, 'O''Higgins', 'XI');  -- Corrected escape for apostrophe
INSERT INTO comuna VALUES(333, 'Tortel', 'XI');
INSERT INTO comuna VALUES(334, 'Chile Chico', 'XI');
INSERT INTO comuna VALUES(335, 'Río Ibáñez', 'XI');

-- Region XII (orden 16): Magallanes
INSERT INTO comuna VALUES(336, 'Punta Arenas', 'XII');
INSERT INTO comuna VALUES(337, 'Laguna Blanca', 'XII');
INSERT INTO comuna VALUES(338, 'Río Verde', 'XII');
INSERT INTO comuna VALUES(339, 'San Gregorio', 'XII');
INSERT INTO comuna VALUES(340, 'Cabo de Hornos', 'XII');
INSERT INTO comuna VALUES(341, 'Antártica', 'XII');
INSERT INTO comuna VALUES(342, 'Porvenir', 'XII');
INSERT INTO comuna VALUES(343, 'Primavera', 'XII');
INSERT INTO comuna VALUES(344, 'Timaukel', 'XII');
INSERT INTO comuna VALUES(345, 'Natales', 'XII');
INSERT INTO comuna VALUES(346, 'Torres del Paine', 'XII');